//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountPartners
    {
        public int Id_discount { get; set; }
        public Nullable<int> Id_partner { get; set; }
        public Nullable<decimal> TotalSalesValue { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
    
        public virtual Partners Partners { get; set; }
    }
}
