//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Logins = new HashSet<Logins>();
            this.Request = new HashSet<Request>();
            this.Workshop = new HashSet<Workshop>();
        }
    
        public int Id_employee { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronumic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PassportSeria { get; set; }
        public string PassportNumber { get; set; }
        public string BankDetails { get; set; }
        public Nullable<int> Id_family { get; set; }
        public Nullable<int> Id_health { get; set; }
        public Nullable<int> Id_role { get; set; }
    
        public virtual FamilyStatus FamilyStatus { get; set; }
        public virtual Health Health { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Logins> Logins { get; set; }
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<Workshop> Workshop { get; set; }
    }
}
