//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.DiscountPartners = new HashSet<DiscountPartners>();
            this.Request = new HashSet<Request>();
            this.SalePoint = new HashSet<SalePoint>();
        }
    
        public int Id_partner { get; set; }
        public string NamePartner { get; set; }
        public Nullable<int> Id_type { get; set; }
        public string UrAdress { get; set; }
        public string INN { get; set; }
        public string SurnameDirector { get; set; }
        public string NameDirector { get; set; }
        public string PatronumicDirector { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public Nullable<decimal> Raiting { get; set; }
    
        public virtual ICollection<DiscountPartners> DiscountPartners { get; set; }
        public virtual TypeOfBusiness TypeOfBusiness { get; set; }
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<SalePoint> SalePoint { get; set; }
    }
}
