//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWorkshop
    {
        public int Id_prodwork { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<int> Id_workshop { get; set; }
        public string TimeMake { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
