//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
            this.ProductWorkshop = new HashSet<ProductWorkshop>();
            this.RequestDetails = new HashSet<RequestDetails>();
            this.SaleHistory = new HashSet<SaleHistory>();
        }
    
        public int Id_product { get; set; }
        public string Articul { get; set; }
        public string NameProduct { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<int> Id_size { get; set; }
        public string WeightNETTO { get; set; }
        public string WeightBRUTTO { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> Id_type { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual SizeUpakovka SizeUpakovka { get; set; }
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
        public virtual ICollection<ProductWorkshop> ProductWorkshop { get; set; }
        public virtual ICollection<RequestDetails> RequestDetails { get; set; }
        public virtual ICollection<SaleHistory> SaleHistory { get; set; }
    }
}
