//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.RequestDetails = new HashSet<RequestDetails>();
        }
    
        public int Id_request { get; set; }
        public Nullable<int> Id_partner { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Id_status { get; set; }
        public Nullable<decimal> TotalAmountReq { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<RequestDetails> RequestDetails { get; set; }
    }
}
