//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleHistory
    {
        public int Id_sale { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Id_point { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual SalePoint SalePoint { get; set; }
    }
}
