//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeUpakovka
    {
        public SizeUpakovka()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id_size { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Length { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
