//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeWorkshop
    {
        public TypeWorkshop()
        {
            this.Workshop = new HashSet<Workshop>();
        }
    
        public int Id_type_workshop { get; set; }
        public string NameTypeWorkshop { get; set; }
    
        public virtual ICollection<Workshop> Workshop { get; set; }
    }
}
