//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMaterial
    {
        public TypeMaterial()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
        }
    
        public int Id_type_material { get; set; }
        public string Name_material { get; set; }
        public Nullable<decimal> LostProcent { get; set; }
    
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
    }
}
