//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfBusiness
    {
        public TypeOfBusiness()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int Id_type { get; set; }
        public string NameBusiness { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
