//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComfortPractice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public Workshop()
        {
            this.ProductWorkshop = new HashSet<ProductWorkshop>();
        }
    
        public int Id_workshop { get; set; }
        public string NameWorkshop { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public Nullable<int> Id_type { get; set; }
        public Nullable<int> Id_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ProductWorkshop> ProductWorkshop { get; set; }
        public virtual TypeWorkshop TypeWorkshop { get; set; }
    }
}
